### ISSUE TITLE
某些菜谱未正确解析，存在null值

### ISSUE THREAD

**Issue by CatKoishi** [tongque0/HowToCook-json#1]
比如尖椒炒牛肉，原料，计算，步骤均为null，但是此菜谱是存在这些项目的
{
  title: '尖椒炒牛肉',
  category: 'meat_dish',
  image: null,
  introduction: '',
  difficulty: '★★★',
  ingredients: null,
  calculations: null,
  steps: null,
  notes: '* 腌制可以加入小苏打使牛肉变嫩，牛肉苏打比例为 500g：3g。* 腌制的时候姜片可用料酒代替，料酒的用量为 3 g/人'
}

**Comment by tongque0** [comment]
感谢您的反馈！  

关于您提到的问题，我会尽快检查并修复程序中存在的解析疏漏。由于原始数据是 Markdown 格式，`calculations` 一栏的解析可能存在一定的不确定性。后续我将优化转换逻辑，并考虑对生成的 JSON 格式进行进一步的精准化处理，确保数据解析更完整、规范。  

同时，未来的 JSON 结构可能会有所调整，以适应数据的格式化需求。敬请关注更新版本，再次感谢您的耐心和支持！

**Comment by tongque0** [comment]
暂时对代码进行了修改，因为之前的官方md可能存在不同的表示格式，以至于解析出错，目前已经加入，但可能并不能覆盖所有的菜品，如有问题，可以随时反馈。
